### ISSUE TITLE
Scrolling by computer mouse is not working

### ISSUE THREAD

**Issue by Kryvokulskyi** [Kryvokulskyi/VAIMObugReports#16]
**Browser:** Chrome 55.0.2883.87
 
**Severity:** minor
**Priority:** low
 
 
**Steps to reproduce:**
 
1. Try scrolling by computer mouse
 
**Actual Result:**
 Scrolling by computer mouse is not working
**Expected result:** 
 Scrolling by computer mouse should be functional

**Comment by mbanin** [comment]
On what page? Only in Chrome 55?

**Comment by Kryvokulskyi** [comment]
Scroll wasn`t working on every page. Retested on Chrome 57, FF, IE, EDGE issue is not reproducable. I`ll try to test on Chrome 55 ( at home) this evening (probably, it may be an invalid issue)

**Comment by Kryvokulskyi** [comment]
The issue is not reproducible. Closing as invalid
